api-docs:
  server: http://localhost:8888/mall
  oauth2:
    authorization-url: http://localhost:8001/oauth2/authorize
    token-url: http://localhost:8001/oauth2/token

springdoc:
  swagger-ui:
    oauth:
      use-basic-authentication-with-access-code-grant: true
  